# permissions for end users to edit dremiorestservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dremiorestserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dremio-rest-server-operator
    app.kubernetes.io/part-of: dremio-rest-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: dremiorestserver-editor-role
rules:
- apiGroups:
  - operator.dremiorestserver.com
  resources:
  - dremiorestservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dremiorestserver.com
  resources:
  - dremiorestservers/status
  verbs:
  - get
